version: 0.0.0.{build}

clone_depth: 1

image: Visual Studio 2026

environment:
  ANDROID_HOME: C:\android-sdk
  JAVA_HOME: C:\Program Files\Java\jdk25

before_build:
  - 'git submodule update --init --recursive'
  - 'move /y "C:\Program Files (x86)\Android\android-sdk" C:\android-sdk'

build_script:
  - gradlew.bat build connectedCheck

after_build:
  - 'appveyor PushArtifact app\build\reports\lint-results-nonRootDebug.html'

deploy: off
