apply plugin: 'com.android.application'

android {
    ndkVersion "27.0.12077973"

    compileSdk 34

    namespace 'com.limelight'

    defaultConfig {
        minSdk 21
        targetSdk 34

        versionName "0.1.0"
        versionCode = 1

        // Generate native debug symbols to allow Google Play to symbolicate our native crashes
        ndk.debugSymbolLevel = 'FULL'
    }

    flavorDimensions.add("root")

    buildFeatures {
        buildConfig = true
    }

    productFlavors {
        root {
            // Android O has native mouse capture, so don't show the rooted
            // version to devices running O on the Play Store.
            maxSdk 25

            externalNativeBuild {
                ndkBuild {
                    arguments "PRODUCT_FLAVOR=root"
                }
            }

            applicationId "dev.prism.iris.root"
            dimension "root"
            buildConfigField "boolean", "ROOT_BUILD", "true"
        }

        nonRoot {
            externalNativeBuild {
                ndkBuild {
                    arguments "PRODUCT_FLAVOR=nonRoot"
                }
            }

            applicationId "dev.prism.iris"
            dimension "root"
            buildConfigField "boolean", "ROOT_BUILD", "false"
        }
    }

    compileOptions {
        encoding "UTF-8"
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    lint {
        disable 'MissingTranslation'
        lintConfig file('lint.xml')
    }

    bundle {
        language {
            // Avoid splitting by language, since we allow users
            // to manually switch language in settings.
            enableSplit = false
        }
        density {
            // FIXME: This should not be necessary but we get
            // weird crashes due to missing drawable resources
            // when this split is enabled.
            enableSplit = false
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            resValue "string", "app_label", "Iris (Debug)"
            resValue "string", "app_label_root", "Iris (Root Debug)"

            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            resValue "string", "app_label", "Iris"
            resValue "string", "app_label_root", "Iris (Root)"

            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            if (System.getenv("IRIS_KEYSTORE_FILE")) {
                signingConfig signingConfigs.create("irisRelease") {
                    storeFile file(System.getenv("IRIS_KEYSTORE_FILE"))
                    storePassword System.getenv("IRIS_KEYSTORE_PASSWORD")
                    keyAlias System.getenv("IRIS_KEY_ALIAS")
                    keyPassword System.getenv("IRIS_KEY_PASSWORD")
                }
            }
        }
    }

    externalNativeBuild {
        ndkBuild {
            path "src/main/jni/Android.mk"
        }
    }
}

dependencies {
    implementation 'org.bouncycastle:bcprov-jdk18on:1.77'
    implementation 'org.bouncycastle:bcpkix-jdk18on:1.77'
    implementation 'org.jcodec:jcodec:0.2.5'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'org.jmdns:jmdns:3.5.9'
    implementation 'com.github.cgutman:ShieldControllerExtensions:1.0.1'
    testImplementation 'junit:junit:4.13.2'
}
